GET http://localhost:8080/eksamen/api/dinner

### Get dinner by id
GET http://localhost:8080/eksamen/api/dinner/id/1
Content-Type: application/json

### Get all dinners
GET http://localhost:8080/eksamen/api/dinner/all
Content-Type: application/json